version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-node
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - "mongo"
  mongo:
    container_name: db_container
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/db/mongo