version: '3'

services:
  api:
    image: node:18.12.0-buster
    container_name: course_book_api
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./:/app"
    command: bash -c "npm install && npm run dev"
    working_dir: "/app"
    depends_on:
      - mongo
    networks:
      - jotter_course_book_front

  mongo:
    container_name: course_book_db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - ./deploy/docker-volumes/mongo:/etc/mongo
    networks:
      - jotter_course_book_front

networks:
  jotter_course_book_front:
    external: true